SET IDENTITY_INSERT [dbo].[State] ON
INSERT INTO [dbo].[State] ([Id], [head], [VisitedFor], [Cities], [weather], [Connectivity], [History], [Religion], [Festivals], [eat], [Buy]) 
VALUES (
1
,N'Andhra Pradesh'
, N'Tirupati (One of the world\u2019s richest  and most visited pilgrimage), Puttaparthi (Ashrama of Satya Sai Baba), Charminar  (the symmetrical Hyderabadi mosque identical to the heritage of Andhra), Golconda  Fort (the kingdom where the largest jewel in the world till date, Kohinoor was  mined), Ramoji Film City (the world class film studio), Qutub Shahi Tombs (1 km  stretch of stoned tombs), Vishakhapatnam (one of the largest and the oldest  Indian shipyard) , etc'
, N'Hyderabad, Visakhapatnam, Vijayawada, Guntur,  Warangal, Nellore'
, N'Summer: March to June, Monsoon: July to  September, Winter: October to February. \u00a0Climate  of Andhra Pradesh is influenced by the South- West Monsoons'
, N'Numerous domestic airports like Tirupati,  Visakhapatnam, Guntur, Secunderabad, Warangal, Vijayawada, dot the landscape of  Andhra and provide comfortable journey to the passengers.Major railway junctions like Hyderabad  Deccan, Adilbad, Adoni, Anantpur, Anakapalle, Bapatta, Basar, Bhimavaram  junction, Bhadrachalam raod, Bhimavaram town, Chittor, Chirala, Cuddapah,  Dhramavaram junction, Eluru, Gooty, Gudivada junction, Gudur Junction, Guntakal  Junction, Kazipet junction, Nalgonda and Nandyal connect Andhra Pradesh on the  network of railways.The network of roads and highways in Andhra  provide it strong connectivity from other major cities of India.'
, N'Made  famous by the Nizams, Qutub Shahis, Vijaynagara and Kakatiya dynasty, Andhra  Pradesh is a destination symbolizing the rich essence of incredible India. Famous  as the cradle of stone architecture, the chronicles of this state are dotted in  the form of illustrious structures, monuments, minarets, stupas and other tomb ruins.  This most visited state of India is known for many tourist attractions,  predominantly for Tirupati, the most visited place of worship in the world. The  state also presents its 3rd century old Buddhist essence ties that can be  experienced during the visit to the ruined stupas and cave complexes at Amaravathi,  Nagarjunakonda, Chandavaram, Thotlakonda to name a few.Bordered by Maharashtra, Chattisgarh and  Orissa in the north, Karnataka in the west, Tamil Nadu in the south and Bay of  Bengal in the east, Andhra Pradesh is the fourth largest area wise state in  India. Krishna and Godavari River run across the state and feed the flourishing  rice bowl of India. Its highest peak, Jindhagada is not only the highest point  in the state, but the highest point in the Eastern Ghats as well. The culture of this state is defined with  an interesting amalgam of its rich traditions. Kuchipudi, the 17th  century state\u2019s dance drama is an inevitable contribution of Andhra to  incredible India. The language of the region, Telugu is the prominent language  preferred for the lyrical composition of Carnatic music. The rich literature is  also not different in Andhra. The deep literary cultural value of Telugu prose  can be reached out from the works of Nannaya, Srinatha, Tikkana, Yerrapragada,  Pothana, Poet Molla and Tarikonda Venkamamba. The modern contributions of  Charles Phillip Brown, Vishwanatha Satyanarayana made the language of the land  a vibrant and evolving expression.The jewel box of Andhra features other  surprising facets as well. The largest gem in the world till date, the  legendary Kohinoor and Hope Diamond were mined in Golconda. The rich region of  Andhra is a mine of rich diamonds, pearls and jewellery traditions, adding on  to the eternal fortunes of the land '
, N'Hinduism and Islam'
, N'Rayalseema Food and Dance Festival,  Tirupati (Sep-Oct),Vijayanagar Dance Festival, Chandragiri  (Oct),Golconda Dance Festival, Hyderabad (Nov),Visaka Utsav and Rushikonda Beach  Festival, Vishakhapatnam (Dec)'
, N'Famous oven baked non-veg Biryani in Hyderabad, Passarettu  Dosa (made of Moong Dal Lentil), tamarind gravies, Gongura (a Roselle plant  chutney), Nellore Fish Curry", " Lacquer bangles from colourful Laad Bazaar, Pearl Jewellery,  Bidriware in Hyderabad'
, N'oftwood toys from Kondapalli and silk saris from Dharmavaram.')
SET IDENTITY_INSERT [dbo].[State] OFF
